sudo: required
services:
  - docker

before_install:
  - docker build -t shivamkhandelwal/react-docker -f Dockerfile.dev .

script:
  - docker run shivamkhandelwal/react-docker npm run test -- --coverage